// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc294.RobotBuilderTest.subsystems;

import org.usfirst.frc294.RobotBuilderTest.RobotMap;
import org.usfirst.frc294.RobotBuilderTest.commands.*;
import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.Solenoid;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Shooter extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
	
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final CANTalon shooterMotorTop = RobotMap.shooterMotorTop;
    private final CANTalon shooterMotorBottom = RobotMap.shooterMotorBottom;
    private final Solenoid shooterPiston = RobotMap.shooterPiston;
    private final DigitalInput intakeButton = RobotMap.intakeButton;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    
    public void setSpeed(double speed){
    	this.shooterMotorTop.set(speed);
    	this.shooterMotorBottom.set(speed);
    }
    
    public double getTopFlyWheelSpeed(){
    	return this.shooterMotorTop.getSpeed();
    }
    
    public double getBottomFlyWheelSpeed(){
    	return this.shooterMotorBottom.getSpeed();
    }
    
    public double getTopError(){
    	return shooterMotorTop.getError();
    }
    
    public double getBottomError(){
    	return shooterMotorBottom.getError();
    }
    
    public boolean isButtonPressed(){
    	return !intakeButton.get();
    }
    
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
}

